;;; agenda-desktop-scroll-test.el --- Native agenda scrolling -*- lexical-binding: t -*-
(require 'ert)
(load (expand-file-name "../config/agenda-desktop-init.el"
                        (file-name-directory load-file-name)) nil t)

(ert-deftest desktop-scroll-keeps-header-and-refresh-position ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((directory (make-temp-file "agenda-scroll-" t))
           (file (expand-file-name "todo.org" directory))
           (org-agenda-files (list file))
           (org-agenda-span 'week)
           (praharsh-agenda-desktop-cache directory)
           (praharsh-agenda-desktop-frame (selected-frame))
           (praharsh-agenda-desktop-stamp nil)
           (date (format-time-string "%Y-%m-%d %a")))
      (unwind-protect
          (cl-letf (((symbol-function 'x-export-frames) (lambda (&rest _) "rendered pixels"))
                    ((symbol-function 'praharsh-org-calendar-sync)
                     (lambda () (ert-fail "Scrolling must not sync Google Calendar"))))
            (with-temp-file file
              (dotimes (i 60)
                (insert (format "* TODO Task %02d\nSCHEDULED: <%s>\n" i date))))
            (praharsh-agenda-desktop-refresh)
            (let* ((body (get-buffer-window "*Org Agenda*"))
                   (header (get-buffer-window "*Agenda Desktop Header*"))
                   (first (window-start body)))
              (should (window-live-p header))
              (should (with-current-buffer (window-buffer header)
                        (string-match-p "Agenda" (buffer-string))))
              (should (eq 'scrolled (praharsh-agenda-desktop-scroll 12 praharsh-agenda-desktop-stamp)))
              (should (> (window-start body) first))
              (should (= (window-start header) 1))
              (let ((top (with-current-buffer (window-buffer body)
                           (save-excursion
                             (goto-char (window-start body))
                             (buffer-substring-no-properties (line-beginning-position) (line-end-position))))))
                ;; A saved insertion above the viewport must not jump the view.
                (with-temp-buffer
                  (insert-file-contents file)
                  (goto-char (point-min))
                  (insert (format "* TODO Added before viewport\nSCHEDULED: <%s>\n" date))
                  (write-region (point-min) (point-max) file nil 'silent))
                (praharsh-agenda-desktop-refresh)
                (with-current-buffer (window-buffer body)
                  (goto-char (window-start body))
                  (should (equal top (buffer-substring-no-properties (line-beginning-position) (line-end-position))))))
              (let ((start (window-start body)))
                (should (eq 'stale (praharsh-agenda-desktop-scroll 3 -1)))
                (should (= start (window-start body))))
              (dotimes (_ 10)
                (praharsh-agenda-desktop-scroll -12 praharsh-agenda-desktop-stamp))
              (should (= first (window-start body)))
              (with-current-buffer (window-buffer body)
                (goto-char (point-max))
                (re-search-backward "^$")
                (set-window-start body (point))
                (set-window-point body (point)))
              (let ((start (window-start body)))
                (praharsh-agenda-desktop-refresh)
                (should (= start (window-start body))))
              (cl-letf (((symbol-function 'x-export-frames) (lambda (&rest _) (error "Export failed"))))
                (should-error (praharsh-agenda-desktop-scroll 3 -1) :type 'user-error))))
        (when-let* ((buffer (get-file-buffer file))) (kill-buffer buffer))
        (delete-directory directory t)))))
