;;; agenda-desktop-test.el --- Desktop agenda check -*- lexical-binding: t -*-
;; Run: emacs -Q --batch -l ~/.emacs.d/test/agenda-desktop-test.el -f ert-run-tests-batch-and-exit
(require 'ert)
(require 'org-agenda)
(load (expand-file-name "../config/agenda-desktop-init.el"
                        (file-name-directory load-file-name)) t t)

(ert-deftest desktop-agenda-renders-org-and-refreshes-saved-tasks ()
  (should (fboundp 'praharsh-agenda-desktop-build))
  ;; Styling must load its faces even before the first Org buffer opens.
  (praharsh-agenda-desktop-style-frame)
  (let* ((file (make-temp-file "desktop-agenda-" nil ".org"))
         (org-agenda-files (list file))
         (org-agenda-span 'week)
         (date (format-time-string "%Y-%m-%d %a"))
         (original-buffer (current-buffer)))
    (unwind-protect
        (progn
          (with-temp-file file
            (insert "* TODO Desktop test task\nSCHEDULED: <" date ">\n"
                    "* TODO A long habit title that must never be overwritten\nSCHEDULED: <"
                    date " .+1d>\n:PROPERTIES:\n:STYLE: habit\n:END:\n"))
          (let ((agenda (praharsh-agenda-desktop-build)))
            (should (eq (current-buffer) original-buffer))
            (with-current-buffer agenda
              (should (string-match-p "Desktop test task" (buffer-string)))
              (should (string-match-p "A long habit title that must never be overwritten" (buffer-string)))
              (should (eq org-agenda-current-span 'week))
              (let ((days 0))
                (goto-char (point-min))
                (should (get-text-property (point) 'agenda-desktop-open))
                (while (not (eobp))
                  (when (and (org-get-at-bol 'org-agenda-date-header) (not (eolp)))
                    (cl-incf days))
                  (forward-line 1))
                (should (= days 7)))
              (should buffer-read-only)
              (should-error (insert "edit") :type 'buffer-read-only)
              (should-not (eq (key-binding (kbd "t")) 'org-agenda-todo))))
          (with-temp-file file
            (insert "* TODO Saved replacement\nSCHEDULED: <" date ">\n"))
          (with-current-buffer (praharsh-agenda-desktop-build)
            (should (string-match-p "Saved replacement" (buffer-string)))
            (should-not (string-match-p "Desktop test task" (buffer-string)))))
      (when-let* ((buffer (get-file-buffer file)))
        (with-current-buffer buffer (set-buffer-modified-p nil))
        (kill-buffer buffer))
      (delete-file file))))

(ert-deftest desktop-failed-render-rejects-clicks-on-old-pixels ()
  (let* ((directory (make-temp-file "desktop-render-" t))
         (praharsh-agenda-desktop-cache directory)
         (file (expand-file-name "todo.org" directory))
         (png (expand-file-name "agenda.png" directory))
         (org-agenda-files (list file))
         (praharsh-agenda-desktop-stamp nil))
    (unwind-protect
        (progn
          (with-temp-file file (insert "* TODO Render test\n"))
          (with-temp-file png (insert "old pixels"))
          (setq praharsh-agenda-desktop-stamp
                (car (time-convert (file-attribute-modification-time (file-attributes png)) 1000000000)))
          (let ((old-stamp praharsh-agenda-desktop-stamp))
            ;; Native frame export is the only GUI dependency in this check.
            (cl-letf (((symbol-function 'x-export-frames)
                       (lambda (&rest _) (error "Export failed"))))
		     (praharsh-agenda-desktop-refresh)
		     (should-not praharsh-agenda-desktop-stamp)
		     (should (eq (praharsh-agenda-desktop-click 50 50 old-stamp) 'stale)))
            (with-temp-buffer
              (insert-file-contents png)
              (should (equal (buffer-string) "old pixels")))))
      (when-let* ((buffer (get-file-buffer file))) (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest desktop-habits-show-done-today-and-todo-tomorrow ()
  (let* ((file (make-temp-file "desktop-habit-" nil ".org"))
         (praharsh-agenda-desktop-cache (make-temp-file "desktop-habit-cache-" t))
         (praharsh-agenda-desktop-history nil)
         (org-agenda-files (list file))
         (org-agenda-span 'week)
         (org-habit-show-habits-only-for-today nil)
         (today (format-time-string "%Y-%m-%d %a"))
         (old (format-time-string "%Y-%m-%d %a" (time-subtract (current-time) (days-to-time 30)))))
    (unwind-protect
        (progn
          (with-temp-file file
            (insert "* TODO Old daily habit\nSCHEDULED: <" old " +1d>\n:PROPERTIES:\n:STYLE: habit\n:END:\n"
                    "* TODO Current daily habit\nSCHEDULED: <" today " .+1d>\n:PROPERTIES:\n:STYLE: habit\n:END:\n"))
          (with-current-buffer (find-file-noselect file)
            (goto-char (point-min))
            (re-search-forward "^\\* TODO Old daily habit")
            (org-back-to-heading)
            (praharsh-agenda-desktop-toggle-task (point-marker))
            (re-search-forward "^\\* TODO Current daily habit")
            (org-back-to-heading)
            (praharsh-agenda-desktop-toggle-task (point-marker))
            (should (equal (org-get-todo-state) "TODO")))
          (with-current-buffer (praharsh-agenda-desktop-build)
            (dolist (title '("Old daily habit" "Current daily habit"))
              (goto-char (point-min))
              (re-search-forward (concat "DONE " title))
              (should (= (org-get-at-bol 'day) (org-today)))
              (should (equal (org-get-at-bol 'todo-state) "DONE"))
              (should (markerp (org-get-at-bol 'org-hd-marker)))))
          (let ((org-agenda-start-day "+1d")
                (org-agenda-span 1))
            (with-current-buffer (praharsh-agenda-desktop-build)
              (should (string-match-p "TODO Current daily habit" (buffer-string)))
              (should-not (string-match-p "DONE Current daily habit" (buffer-string))))))
      (when-let* ((buffer (get-file-buffer file)))
        (with-current-buffer buffer (set-buffer-modified-p nil))
        (kill-buffer buffer))
      (delete-file file)
      (delete-directory praharsh-agenda-desktop-cache t))))

(ert-deftest desktop-click-toggles-safely-with-native-org-repeat ()
  (should (fboundp 'praharsh-agenda-desktop-toggle-task))
  (let* ((file (make-temp-file "desktop-click-" nil ".org"))
         (praharsh-agenda-desktop-cache (make-temp-file "desktop-click-cache-" t))
         (praharsh-agenda-desktop-history nil)
         (org-agenda-files (list file))
         (org-log-done 'note)
         (org-log-repeat 'note)
         (date (format-time-string "%Y-%m-%d %a")))
    (unwind-protect
        (progn
          (with-temp-file file
            (insert "#+TODO: TODO(t) | DONE(d@) CANCELED(c@)\n"
                    "* TODO Click task\nSCHEDULED: <" date ">\n"
                    ":PROPERTIES:\n:LOGGING: lognotedone\n:END:\n"
                    "* TODO Repeat task\nSCHEDULED: <" date " .+1d>\n"
                    ":PROPERTIES:\n:STYLE: habit\n:LOGGING: lognoterepeat\n:END:\n"))
          (let ((buffer (find-file-noselect file)))
            (with-current-buffer buffer
              (goto-char (point-min))
              (re-search-forward "^\\* TODO Click task")
              (org-back-to-heading)
              (praharsh-agenda-desktop-toggle-task (point-marker))
              (should (equal (org-get-todo-state) "DONE"))
              (should (org-entry-get nil "CLOSED"))
              (should-not (buffer-modified-p))
              ;; Completed ordinary tasks can be reopened and saved.
              (should (eq (praharsh-agenda-desktop-toggle-task (point-marker)) 'todo))
              (should (equal (org-get-todo-state) "TODO"))
              (should-not (org-entry-get nil "CLOSED"))
              (should-not (buffer-modified-p))
              (re-search-forward "^\\* TODO Repeat task")
              (org-back-to-heading)
              (let ((before (praharsh-agenda-desktop-entry-text)))
		(praharsh-agenda-desktop-toggle-task (point-marker))
		(should (equal (org-get-todo-state) "TODO"))
		(should (org-entry-get nil "LAST_REPEAT"))
		(should-not (string-match-p (regexp-quote date) (org-entry-get nil "SCHEDULED")))
		(should-not (buffer-modified-p))
		;; Reload persisted history, then restore the exact prior entry.
		(setq praharsh-agenda-desktop-history :unloaded)
		(should (eq (praharsh-agenda-desktop-toggle-task (point-marker)) 'todo))
		(should (equal before (praharsh-agenda-desktop-entry-text)))
		(should-not (buffer-modified-p)))
              ;; Refuse source edits that have not been saved.
              (insert " ")
              (should-error (praharsh-agenda-desktop-toggle-task (point-marker)) :type 'user-error)
              (revert-buffer t t)
              (goto-char (point-min))
              (re-search-forward "^\\* TODO Click task")
              (org-back-to-heading)
              (let ((marker (point-marker)))
                (with-temp-file file (insert "* TODO Externally replaced\n"))
                (should-error (praharsh-agenda-desktop-toggle-task marker) :type 'user-error))))
          (with-temp-buffer
            (insert-file-contents file)
            (should (equal (buffer-string) "* TODO Externally replaced\n"))))
      (when-let* ((buffer (get-file-buffer file)))
        (with-current-buffer buffer (set-buffer-modified-p nil))
        (kill-buffer buffer))
      (delete-file file)
      (delete-directory praharsh-agenda-desktop-cache t))))

(ert-deftest desktop-habit-undo-protects-saved-edits-and-cache-failures ()
  (let* ((file (make-temp-file "desktop-undo-" nil ".org"))
         (praharsh-agenda-desktop-cache (make-temp-file "desktop-undo-cache-" t))
         (praharsh-agenda-desktop-history nil)
         (org-agenda-files (list file))
         (original (concat "* TODO Undo test\nSCHEDULED: <" (format-time-string "%Y-%m-%d %a")
                           " .+1d>\n:PROPERTIES:\n:STYLE: habit\n:END:\n")))
    (unwind-protect
        (progn
          (with-temp-file file (insert original))
          (with-current-buffer (find-file-noselect file)
            (goto-char (point-min))
            (let ((marker (point-marker)))
              (cl-letf (((symbol-function 'praharsh-agenda-desktop-save-history)
                         (lambda (&rest _) (error "Cache write failed"))))
                       (should-error (praharsh-agenda-desktop-toggle-task marker)))
              (should (equal original (buffer-substring-no-properties (point-min) (point-max))))
              (should-not (buffer-modified-p))
              (praharsh-agenda-desktop-toggle-task marker)
              (goto-char (point-max))
              (insert "User saved note\n")
              (save-buffer)
              (let ((edited (buffer-substring-no-properties (point-min) (point-max))))
                (should-error (praharsh-agenda-desktop-toggle-task marker) :type 'user-error)
                (should (equal edited (buffer-substring-no-properties (point-min) (point-max))))))))
      (when-let* ((buffer (get-file-buffer file)))
        (with-current-buffer buffer (set-buffer-modified-p nil))
        (kill-buffer buffer))
      (delete-file file)
      (delete-directory praharsh-agenda-desktop-cache t))))
